Fix build error Error C2872 'byte': ambiguous symbol when building on VS2017 with the ISO C++17 Standard (/std:c++17) language standard set.
Now that there is std::byte in C++17 it's getting confused with a Windows type of the same name.  Moving 'using namespace std' after the Windows.h include solves it.
https://developercommunity.visualstudio.com/content/problem/93889/error-c2872-byte-ambiguous-symbol.html

Personally, I prefer omitting 'using namespace' and writing the namespace where needed so it's clear where everything comes from.